module "CCArray"

function create() end
function createWithObject() end
function createWithArray() end
function createWithCapacity() end
function createWithContentsOfFile() end
function count() end
function capacity() end
function indexOfObject() end
function objectAtIndex() end
function lastObject() end
function randomObject() end
function isEqualToArray() end
function containsObject() end
function addObject() end
function addObjectsFromArray() end
function insertObject() end
function removeLastObject() end
function removeObject() end
function removeObjectAtIndex() end
function removeObjectsInArray() end
function removeAllObjects() end
function fastRemoveObject() end
function fastRemoveObjectAtIndex() end
function exchangeObject() end
function exchangeObjectAtIndex() end
function reverseObjects() end
function replaceObjectAtIndex() end
function reduceMemoryFootprint() end
