module "CCNode"

function getZOrder() end
function setZOrder() end
function getVertexZ() end
function setVertexZ() end
function getRotation() end
function setRotation() end
function getScale() end
function setScale() end
function getScaleX() end
function setScaleX() end
function getScaleY() end
function setScaleY() end
function getPosition() end
function getPositionX() end
function getPositionY() end
function setPosition() end
function setPosition() end
function setPositionX() end
function setPositionY() end
function getSkewX() end
function setSkewX() end
function getSkewY() end
function setSkewY() end
function isVisible() end
function setVisible() end
function getAnchorPoint() end
function getAnchorPointInPoints() end
function setAnchorPoint() end
function getContentSize() end
function setContentSize() end
function getTag() end
function setTag() end
function getCamera() end
function isRunning() end
function isIgnoreAnchorPointForPosition() end
function ignoreAnchorPointForPosition() end
function getUserObject() end
function setUserObject() end
function getOrderOfArrival() end
function setOrderOfArrival() end
function getParent() end
function setParent() end
function getChildren() end
function getChildrenCount() end
function getChildByTag() end
function addChild() end
function addChild() end
function addChild() end
function removeChild() end
function removeChildByTag() end
function removeAllChildrenWithCleanup() end
function reorderChild() end
function cleanup() end
function visit() end
function transform() end
function transformAncestors() end
function boundingBox() end
function runAction() end
function stopAllActions() end
function stopAction() end
function stopActionByTag() end
function getActionByTag() end
function description() end
function numberOfRunningActions() end
function convertToNodeSpace() end
function convertToWorldSpace() end
function convertToNodeSpaceAR() end
function convertToWorldSpaceAR() end
function convertTouchToNodeSpace() end
function convertTouchToNodeSpaceAR() end
function removeFromParentAndCleanup() end
function scheduleUpdateWithPriorityLua() end
function unscheduleUpdate() end
function registerScriptHandler() end
function unregisterScriptHandler() end
