module "CCParticleSystemQuad"

function getGravity() end
function setGravity() end
function getSpeed() end
function setSpeed() end
function getSpeedVar() end
function setSpeedVar() end
function getTangentialAccel() end
function setTangentialAccel() end
function getTangentialAccelVar() end
function setTangentialAccelVar() end
function getRadialAccel() end
function setRadialAccel() end
function getRadialAccelVar() end
function setRadialAccelVar() end
function getStartRadius() end
function setStartRadius() end
function getStartRadiusVar() end
function setStartRadiusVar() end
function getEndRadius() end
function setEndRadius() end
function getEndRadiusVar() end
function setEndRadiusVar() end
function getRotatePerSecond() end
function setRotatePerSecond() end
function getRotatePerSecondVar() end
function setRotatePerSecondVar() end
function addParticle() end
function initParticle() end
function stopSystem() end
function resetSystem() end
function isFull() end
function updateQuadWithParticle() end
function postStep() end
function getParticleCount() end
function getDuration() end
function setDuration() end
function getSourcePosition() end
function setSourcePosition() end
function getPosVar() end
function setPosVar() end
function getLife() end
function setLife() end
function getLifeVar() end
function setLifeVar() end
function getAngle() end
function setAngle() end
function getAngleVar() end
function setAngleVar() end
function getStartSize() end
function setStartSize() end
function getStartSizeVar() end
function setStartSizeVar() end
function getEndSize() end
function setEndSize() end
function getEndSizeVar() end
function setEndSizeVar() end
function setStartColor() end
function getStartColor() end
function setStartColorVar() end
function getStartColorVar() end
function setEndColor() end
function getEndColor() end
function setEndColorVar() end
function getEndColorVar() end
function setStartSpin() end
function getStartSpin() end
function setStartSpinVar() end
function getStartSpinVar() end
function setEndSpin() end
function getEndSpin() end
function setEndSpinVar() end
function getEndSpinVar() end
function setEmissionRate() end
function getEmissionRate() end
function getTotalParticles() end
function isAutoRemoveOnFinish() end
function setAutoRemoveOnFinish() end
function getEmitterMode() end
function setEmitterMode() end
function getTexture() end
function setTexture() end
function getBlendFunc() end
function setBlendFunc() end
function setScale() end
function setRotation() end
function setScaleX() end
function setScaleY() end
function isActive() end
function isBlendAdditive() end
function setBlendAdditive() end
function getBatchNode() end
function setBatchNode() end
function getPositionType() end
function setPositionType() end
function postStep() end
function setDisplayFrame() end
function setTexture() end
function setTextureWithRect() end
function setBatchNode() end
function setTotalParticles() end
function updateQuadWithParticle() end
function postStep() end
function setTotalParticles() end
function create() end
function create() end
