module "CCSprite"

function setDirty() end
function isDirty() end
function getTextureRect() end
function isTextureRectRotated() end
function setAtlasIndex() end
function getAtlasIndex() end
function setBlendFunc() end
function getBlendFunc() end
function getOffsetPosition() end
function setFlipX() end
function setFlipY() end
function isFlipX() end
function isFlipY() end
function setOpacity() end
function getOpacity() end
function setColor() end
function getColor() end
function setOpacityModifyRGB() end
function isOpacityModifyRGB() end
function setTexture() end
function getTexture() end
function updateTransform() end
function setTextureRect() end
function setTextureRect() end
function setVertexRect() end
function setDisplayFrame() end
function isFrameDisplayed() end
function displayFrame() end
function setBatchNode() end
function getBatchNode() end
function setDisplayFrameWithAnimationName() end
function createWithTexture() end
function createWithTexture() end
function createWithSpriteFrame() end
function createWithSpriteFrameName() end
function create() end
function create() end
function create() end
